apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.env }}-lang-detector
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 30100
  selector:
    app: {{ .Values.env }}-lang-detector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.env }}-lang-detector
  labels:
    app: {{ .Values.env }}-lang-detector
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.env }}-lang-detector
  template:
    metadata:
      annotations:
        timestamp: "{{ .Values.timestamp }}"
      labels:
        app: {{ .Values.env }}-lang-detector
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: lang-detector
          image: 9rga/go-lang-detector
          command: ["/bin/sh", "-c", "/opt/detector -port 80"]
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
